#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bleys.Droid.Resource", IsApplication=true)]

namespace Bleys.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Bleys.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromLeft = global::Bleys.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromRight = global::Bleys.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToLeft = global::Bleys.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToRight = global::Bleys.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardBackgroundColor = global::Bleys.Droid.Resource.Attribute.cardBackgroundColor;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardCornerRadius = global::Bleys.Droid.Resource.Attribute.cardCornerRadius;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardElevation = global::Bleys.Droid.Resource.Attribute.cardElevation;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardMaxElevation = global::Bleys.Droid.Resource.Attribute.cardMaxElevation;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardPreventCornerOverlap = global::Bleys.Droid.Resource.Attribute.cardPreventCornerOverlap;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardUseCompatPadding = global::Bleys.Droid.Resource.Attribute.cardUseCompatPadding;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.cardViewStyle = global::Bleys.Droid.Resource.Attribute.cardViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.contentPadding = global::Bleys.Droid.Resource.Attribute.contentPadding;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.contentPaddingBottom = global::Bleys.Droid.Resource.Attribute.contentPaddingBottom;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.contentPaddingLeft = global::Bleys.Droid.Resource.Attribute.contentPaddingLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.contentPaddingRight = global::Bleys.Droid.Resource.Attribute.contentPaddingRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.contentPaddingTop = global::Bleys.Droid.Resource.Attribute.contentPaddingTop;
			global::Xamarin.Forms.Platform.Android.Resource.Color.cardview_dark_background = global::Bleys.Droid.Resource.Color.cardview_dark_background;
			global::Xamarin.Forms.Platform.Android.Resource.Color.cardview_light_background = global::Bleys.Droid.Resource.Color.cardview_light_background;
			global::Xamarin.Forms.Platform.Android.Resource.Color.cardview_shadow_end_color = global::Bleys.Droid.Resource.Color.cardview_shadow_end_color;
			global::Xamarin.Forms.Platform.Android.Resource.Color.cardview_shadow_start_color = global::Bleys.Droid.Resource.Color.cardview_shadow_start_color;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.cardview_compat_inset_shadow = global::Bleys.Droid.Resource.Dimension.cardview_compat_inset_shadow;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.cardview_default_elevation = global::Bleys.Droid.Resource.Dimension.cardview_default_elevation;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.cardview_default_radius = global::Bleys.Droid.Resource.Dimension.cardview_default_radius;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_corner_radius = global::Bleys.Droid.Resource.Dimension.mtrl_btn_corner_radius;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_dialog_btn_min_width = global::Bleys.Droid.Resource.Dimension.mtrl_btn_dialog_btn_min_width;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_disabled_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_elevation;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_disabled_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_z;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_elevation;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_focused_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_focused_z;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_hovered_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_hovered_z;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_icon_padding;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_inset = global::Bleys.Droid.Resource.Dimension.mtrl_btn_inset;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_letter_spacing = global::Bleys.Droid.Resource.Dimension.mtrl_btn_letter_spacing;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_padding_bottom = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_bottom;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_left;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_right;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_padding_top = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_top;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_pressed_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_pressed_z;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_stroke_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_stroke_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_text_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_icon_padding;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_text_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_left;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_text_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_right;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_text_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.mtrl_btn_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_z;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_navarea = global::Bleys.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_tabbar = global::Bleys.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::Bleys.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_recycler = global::Bleys.Droid.Resource.Id.flyoutcontent_recycler;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_appbar = global::Bleys.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_tablayout = global::Bleys.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_toolbar = global::Bleys.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_viewpager = global::Bleys.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_appbar = global::Bleys.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_toolbar = global::Bleys.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.sliding_tabs = global::Bleys.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Id.toolbar = global::Bleys.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.BottomTabLayout = global::Bleys.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackTabbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackToolbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FlyoutContent = global::Bleys.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.RootLayout = global::Bleys.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.ShellContent = global::Bleys.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Tabbar = global::Bleys.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::Bleys.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Base_CardView = global::Bleys.Droid.Resource.Style.Base_CardView;
			global::Xamarin.Forms.Platform.Android.Resource.Style.CardView = global::Bleys.Droid.Resource.Style.CardView;
			global::Xamarin.Forms.Platform.Android.Resource.Style.CardView_Dark = global::Bleys.Droid.Resource.Style.CardView_Dark;
			global::Xamarin.Forms.Platform.Android.Resource.Style.CardView_Light = global::Bleys.Droid.Resource.Style.CardView_Light;
			global::Xamarin.Forms.Platform.Android.Resource.Style.collectionViewStyle = global::Bleys.Droid.Resource.Style.collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Style.NestedScrollBarStyle = global::Bleys.Droid.Resource.Style.NestedScrollBarStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView = global::Bleys.Droid.Resource.Styleable.CardView;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_android_minHeight = global::Bleys.Droid.Resource.Styleable.CardView_android_minHeight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_android_minWidth = global::Bleys.Droid.Resource.Styleable.CardView_android_minWidth;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardBackgroundColor = global::Bleys.Droid.Resource.Styleable.CardView_cardBackgroundColor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardCornerRadius = global::Bleys.Droid.Resource.Styleable.CardView_cardCornerRadius;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardElevation;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardMaxElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardMaxElevation;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardPreventCornerOverlap = global::Bleys.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_cardUseCompatPadding = global::Bleys.Droid.Resource.Styleable.CardView_cardUseCompatPadding;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_contentPadding = global::Bleys.Droid.Resource.Styleable.CardView_contentPadding;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_contentPaddingBottom = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingBottom;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_contentPaddingLeft = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_contentPaddingRight = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingRight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CardView_contentPaddingTop = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingTop;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromLeft = global::Bleys.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromRight = global::Bleys.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToLeft = global::Bleys.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToRight = global::Bleys.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardBackgroundColor = global::Bleys.Droid.Resource.Attribute.cardBackgroundColor;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardCornerRadius = global::Bleys.Droid.Resource.Attribute.cardCornerRadius;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardElevation = global::Bleys.Droid.Resource.Attribute.cardElevation;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardMaxElevation = global::Bleys.Droid.Resource.Attribute.cardMaxElevation;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardPreventCornerOverlap = global::Bleys.Droid.Resource.Attribute.cardPreventCornerOverlap;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardUseCompatPadding = global::Bleys.Droid.Resource.Attribute.cardUseCompatPadding;
			global::Xamarin.Forms.Platform.Resource.Attribute.cardViewStyle = global::Bleys.Droid.Resource.Attribute.cardViewStyle;
			global::Xamarin.Forms.Platform.Resource.Attribute.contentPadding = global::Bleys.Droid.Resource.Attribute.contentPadding;
			global::Xamarin.Forms.Platform.Resource.Attribute.contentPaddingBottom = global::Bleys.Droid.Resource.Attribute.contentPaddingBottom;
			global::Xamarin.Forms.Platform.Resource.Attribute.contentPaddingLeft = global::Bleys.Droid.Resource.Attribute.contentPaddingLeft;
			global::Xamarin.Forms.Platform.Resource.Attribute.contentPaddingRight = global::Bleys.Droid.Resource.Attribute.contentPaddingRight;
			global::Xamarin.Forms.Platform.Resource.Attribute.contentPaddingTop = global::Bleys.Droid.Resource.Attribute.contentPaddingTop;
			global::Xamarin.Forms.Platform.Resource.Color.cardview_dark_background = global::Bleys.Droid.Resource.Color.cardview_dark_background;
			global::Xamarin.Forms.Platform.Resource.Color.cardview_light_background = global::Bleys.Droid.Resource.Color.cardview_light_background;
			global::Xamarin.Forms.Platform.Resource.Color.cardview_shadow_end_color = global::Bleys.Droid.Resource.Color.cardview_shadow_end_color;
			global::Xamarin.Forms.Platform.Resource.Color.cardview_shadow_start_color = global::Bleys.Droid.Resource.Color.cardview_shadow_start_color;
			global::Xamarin.Forms.Platform.Resource.Dimension.cardview_compat_inset_shadow = global::Bleys.Droid.Resource.Dimension.cardview_compat_inset_shadow;
			global::Xamarin.Forms.Platform.Resource.Dimension.cardview_default_elevation = global::Bleys.Droid.Resource.Dimension.cardview_default_elevation;
			global::Xamarin.Forms.Platform.Resource.Dimension.cardview_default_radius = global::Bleys.Droid.Resource.Dimension.cardview_default_radius;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_corner_radius = global::Bleys.Droid.Resource.Dimension.mtrl_btn_corner_radius;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_dialog_btn_min_width = global::Bleys.Droid.Resource.Dimension.mtrl_btn_dialog_btn_min_width;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_disabled_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_elevation;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_disabled_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_z;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_elevation;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_focused_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_focused_z;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_hovered_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_hovered_z;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_icon_padding;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_inset = global::Bleys.Droid.Resource.Dimension.mtrl_btn_inset;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_letter_spacing = global::Bleys.Droid.Resource.Dimension.mtrl_btn_letter_spacing;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_padding_bottom = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_bottom;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_left;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_right;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_padding_top = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_top;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_pressed_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_pressed_z;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_stroke_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_stroke_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_text_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_icon_padding;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_text_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_left;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_text_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_right;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_text_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_size;
			global::Xamarin.Forms.Platform.Resource.Dimension.mtrl_btn_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_z;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_navarea = global::Bleys.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_tabbar = global::Bleys.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Resource.Id.flyoutcontent_appbar = global::Bleys.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.flyoutcontent_recycler = global::Bleys.Droid.Resource.Id.flyoutcontent_recycler;
			global::Xamarin.Forms.Platform.Resource.Id.main_appbar = global::Bleys.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_tablayout = global::Bleys.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Resource.Id.main_toolbar = global::Bleys.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_viewpager = global::Bleys.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_appbar = global::Bleys.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_toolbar = global::Bleys.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.sliding_tabs = global::Bleys.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Resource.Id.toolbar = global::Bleys.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Resource.Layout.BottomTabLayout = global::Bleys.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackTabbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackToolbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FlyoutContent = global::Bleys.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Resource.Layout.RootLayout = global::Bleys.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.ShellContent = global::Bleys.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Resource.Layout.Tabbar = global::Bleys.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Resource.Layout.Toolbar = global::Bleys.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Resource.Style.Base_CardView = global::Bleys.Droid.Resource.Style.Base_CardView;
			global::Xamarin.Forms.Platform.Resource.Style.CardView = global::Bleys.Droid.Resource.Style.CardView;
			global::Xamarin.Forms.Platform.Resource.Style.CardView_Dark = global::Bleys.Droid.Resource.Style.CardView_Dark;
			global::Xamarin.Forms.Platform.Resource.Style.CardView_Light = global::Bleys.Droid.Resource.Style.CardView_Light;
			global::Xamarin.Forms.Platform.Resource.Style.collectionViewStyle = global::Bleys.Droid.Resource.Style.collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Style.NestedScrollBarStyle = global::Bleys.Droid.Resource.Style.NestedScrollBarStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView = global::Bleys.Droid.Resource.Styleable.CardView;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_android_minHeight = global::Bleys.Droid.Resource.Styleable.CardView_android_minHeight;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_android_minWidth = global::Bleys.Droid.Resource.Styleable.CardView_android_minWidth;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardBackgroundColor = global::Bleys.Droid.Resource.Styleable.CardView_cardBackgroundColor;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardCornerRadius = global::Bleys.Droid.Resource.Styleable.CardView_cardCornerRadius;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardElevation;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardMaxElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardMaxElevation;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardPreventCornerOverlap = global::Bleys.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_cardUseCompatPadding = global::Bleys.Droid.Resource.Styleable.CardView_cardUseCompatPadding;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_contentPadding = global::Bleys.Droid.Resource.Styleable.CardView_contentPadding;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_contentPaddingBottom = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingBottom;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_contentPaddingLeft = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingLeft;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_contentPaddingRight = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingRight;
			global::Xamarin.Forms.Platform.Resource.Styleable.CardView_contentPaddingTop = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingTop;
			global::XF.Material.Resource.Animation.EnterFromLeft = global::Bleys.Droid.Resource.Animation.EnterFromLeft;
			global::XF.Material.Resource.Animation.EnterFromRight = global::Bleys.Droid.Resource.Animation.EnterFromRight;
			global::XF.Material.Resource.Animation.ExitToLeft = global::Bleys.Droid.Resource.Animation.ExitToLeft;
			global::XF.Material.Resource.Animation.ExitToRight = global::Bleys.Droid.Resource.Animation.ExitToRight;
			global::XF.Material.Resource.Animator.material_button_state_list_anim = global::Bleys.Droid.Resource.Animator.material_button_state_list_anim;
			global::XF.Material.Resource.Attribute.cardBackgroundColor = global::Bleys.Droid.Resource.Attribute.cardBackgroundColor;
			global::XF.Material.Resource.Attribute.cardCornerRadius = global::Bleys.Droid.Resource.Attribute.cardCornerRadius;
			global::XF.Material.Resource.Attribute.cardElevation = global::Bleys.Droid.Resource.Attribute.cardElevation;
			global::XF.Material.Resource.Attribute.cardMaxElevation = global::Bleys.Droid.Resource.Attribute.cardMaxElevation;
			global::XF.Material.Resource.Attribute.cardPreventCornerOverlap = global::Bleys.Droid.Resource.Attribute.cardPreventCornerOverlap;
			global::XF.Material.Resource.Attribute.cardUseCompatPadding = global::Bleys.Droid.Resource.Attribute.cardUseCompatPadding;
			global::XF.Material.Resource.Attribute.cardViewStyle = global::Bleys.Droid.Resource.Attribute.cardViewStyle;
			global::XF.Material.Resource.Attribute.contentPadding = global::Bleys.Droid.Resource.Attribute.contentPadding;
			global::XF.Material.Resource.Attribute.contentPaddingBottom = global::Bleys.Droid.Resource.Attribute.contentPaddingBottom;
			global::XF.Material.Resource.Attribute.contentPaddingLeft = global::Bleys.Droid.Resource.Attribute.contentPaddingLeft;
			global::XF.Material.Resource.Attribute.contentPaddingRight = global::Bleys.Droid.Resource.Attribute.contentPaddingRight;
			global::XF.Material.Resource.Attribute.contentPaddingTop = global::Bleys.Droid.Resource.Attribute.contentPaddingTop;
			global::XF.Material.Resource.Attribute.lottie_autoPlay = global::Bleys.Droid.Resource.Attribute.lottie_autoPlay;
			global::XF.Material.Resource.Attribute.lottie_cacheComposition = global::Bleys.Droid.Resource.Attribute.lottie_cacheComposition;
			global::XF.Material.Resource.Attribute.lottie_colorFilter = global::Bleys.Droid.Resource.Attribute.lottie_colorFilter;
			global::XF.Material.Resource.Attribute.lottie_enableMergePathsForKitKatAndAbove = global::Bleys.Droid.Resource.Attribute.lottie_enableMergePathsForKitKatAndAbove;
			global::XF.Material.Resource.Attribute.lottie_fallbackRes = global::Bleys.Droid.Resource.Attribute.lottie_fallbackRes;
			global::XF.Material.Resource.Attribute.lottie_fileName = global::Bleys.Droid.Resource.Attribute.lottie_fileName;
			global::XF.Material.Resource.Attribute.lottie_imageAssetsFolder = global::Bleys.Droid.Resource.Attribute.lottie_imageAssetsFolder;
			global::XF.Material.Resource.Attribute.lottie_loop = global::Bleys.Droid.Resource.Attribute.lottie_loop;
			global::XF.Material.Resource.Attribute.lottie_progress = global::Bleys.Droid.Resource.Attribute.lottie_progress;
			global::XF.Material.Resource.Attribute.lottie_rawRes = global::Bleys.Droid.Resource.Attribute.lottie_rawRes;
			global::XF.Material.Resource.Attribute.lottie_renderMode = global::Bleys.Droid.Resource.Attribute.lottie_renderMode;
			global::XF.Material.Resource.Attribute.lottie_repeatCount = global::Bleys.Droid.Resource.Attribute.lottie_repeatCount;
			global::XF.Material.Resource.Attribute.lottie_repeatMode = global::Bleys.Droid.Resource.Attribute.lottie_repeatMode;
			global::XF.Material.Resource.Attribute.lottie_scale = global::Bleys.Droid.Resource.Attribute.lottie_scale;
			global::XF.Material.Resource.Attribute.lottie_speed = global::Bleys.Droid.Resource.Attribute.lottie_speed;
			global::XF.Material.Resource.Attribute.lottie_url = global::Bleys.Droid.Resource.Attribute.lottie_url;
			global::XF.Material.Resource.Color.cardview_dark_background = global::Bleys.Droid.Resource.Color.cardview_dark_background;
			global::XF.Material.Resource.Color.cardview_light_background = global::Bleys.Droid.Resource.Color.cardview_light_background;
			global::XF.Material.Resource.Color.cardview_shadow_end_color = global::Bleys.Droid.Resource.Color.cardview_shadow_end_color;
			global::XF.Material.Resource.Color.cardview_shadow_start_color = global::Bleys.Droid.Resource.Color.cardview_shadow_start_color;
			global::XF.Material.Resource.Dimension.cardview_compat_inset_shadow = global::Bleys.Droid.Resource.Dimension.cardview_compat_inset_shadow;
			global::XF.Material.Resource.Dimension.cardview_default_elevation = global::Bleys.Droid.Resource.Dimension.cardview_default_elevation;
			global::XF.Material.Resource.Dimension.cardview_default_radius = global::Bleys.Droid.Resource.Dimension.cardview_default_radius;
			global::XF.Material.Resource.Dimension.mtrl_btn_additional_padding_end_for_icon = global::Bleys.Droid.Resource.Dimension.mtrl_btn_additional_padding_end_for_icon;
			global::XF.Material.Resource.Dimension.mtrl_btn_additional_padding_start_for_icon = global::Bleys.Droid.Resource.Dimension.mtrl_btn_additional_padding_start_for_icon;
			global::XF.Material.Resource.Dimension.mtrl_btn_corner_radius = global::Bleys.Droid.Resource.Dimension.mtrl_btn_corner_radius;
			global::XF.Material.Resource.Dimension.mtrl_btn_dialog_btn_min_width = global::Bleys.Droid.Resource.Dimension.mtrl_btn_dialog_btn_min_width;
			global::XF.Material.Resource.Dimension.mtrl_btn_disabled_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_elevation;
			global::XF.Material.Resource.Dimension.mtrl_btn_disabled_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_disabled_z;
			global::XF.Material.Resource.Dimension.mtrl_btn_elevation = global::Bleys.Droid.Resource.Dimension.mtrl_btn_elevation;
			global::XF.Material.Resource.Dimension.mtrl_btn_focused_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_focused_z;
			global::XF.Material.Resource.Dimension.mtrl_btn_hovered_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_hovered_z;
			global::XF.Material.Resource.Dimension.mtrl_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_icon_padding;
			global::XF.Material.Resource.Dimension.mtrl_btn_inset = global::Bleys.Droid.Resource.Dimension.mtrl_btn_inset;
			global::XF.Material.Resource.Dimension.mtrl_btn_letter_spacing = global::Bleys.Droid.Resource.Dimension.mtrl_btn_letter_spacing;
			global::XF.Material.Resource.Dimension.mtrl_btn_padding_bottom = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_bottom;
			global::XF.Material.Resource.Dimension.mtrl_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_left;
			global::XF.Material.Resource.Dimension.mtrl_btn_padding_left_with_icon = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_left_with_icon;
			global::XF.Material.Resource.Dimension.mtrl_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_right;
			global::XF.Material.Resource.Dimension.mtrl_btn_padding_top = global::Bleys.Droid.Resource.Dimension.mtrl_btn_padding_top;
			global::XF.Material.Resource.Dimension.mtrl_btn_pressed_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_pressed_z;
			global::XF.Material.Resource.Dimension.mtrl_btn_stroke_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_stroke_size;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_btn_icon_padding = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_icon_padding;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_btn_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_left;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_btn_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_btn_padding_right;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_padding_left = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_padding_left;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_padding_right = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_padding_right;
			global::XF.Material.Resource.Dimension.mtrl_btn_text_size = global::Bleys.Droid.Resource.Dimension.mtrl_btn_text_size;
			global::XF.Material.Resource.Dimension.mtrl_btn_z = global::Bleys.Droid.Resource.Dimension.mtrl_btn_z;
			global::XF.Material.Resource.Drawable.drawable_ripple = global::Bleys.Droid.Resource.Drawable.drawable_ripple;
			global::XF.Material.Resource.Drawable.drawable_ripple_image = global::Bleys.Droid.Resource.Drawable.drawable_ripple_image;
			global::XF.Material.Resource.Drawable.drawable_ripple_outlined = global::Bleys.Droid.Resource.Drawable.drawable_ripple_outlined;
			global::XF.Material.Resource.Drawable.drawable_ripple_outlined_with_icon = global::Bleys.Droid.Resource.Drawable.drawable_ripple_outlined_with_icon;
			global::XF.Material.Resource.Drawable.drawable_ripple_text = global::Bleys.Droid.Resource.Drawable.drawable_ripple_text;
			global::XF.Material.Resource.Drawable.drawable_ripple_with_icon = global::Bleys.Droid.Resource.Drawable.drawable_ripple_with_icon;
			global::XF.Material.Resource.Drawable.drawable_selector = global::Bleys.Droid.Resource.Drawable.drawable_selector;
			global::XF.Material.Resource.Drawable.drawable_shape = global::Bleys.Droid.Resource.Drawable.drawable_shape;
			global::XF.Material.Resource.Drawable.drawable_shape_text = global::Bleys.Droid.Resource.Drawable.drawable_shape_text;
			global::XF.Material.Resource.Drawable.drawable_shape_with_icon = global::Bleys.Droid.Resource.Drawable.drawable_shape_with_icon;
			global::XF.Material.Resource.Drawable.xf_arrow_dropdown = global::Bleys.Droid.Resource.Drawable.xf_arrow_dropdown;
			global::XF.Material.Resource.Drawable.xf_check = global::Bleys.Droid.Resource.Drawable.xf_check;
			global::XF.Material.Resource.Drawable.xf_checkbox_selected = global::Bleys.Droid.Resource.Drawable.xf_checkbox_selected;
			global::XF.Material.Resource.Drawable.xf_checkbox_unselected = global::Bleys.Droid.Resource.Drawable.xf_checkbox_unselected;
			global::XF.Material.Resource.Drawable.xf_clear = global::Bleys.Droid.Resource.Drawable.xf_clear;
			global::XF.Material.Resource.Drawable.xf_error = global::Bleys.Droid.Resource.Drawable.xf_error;
			global::XF.Material.Resource.Drawable.xf_radio_button_selected = global::Bleys.Droid.Resource.Drawable.xf_radio_button_selected;
			global::XF.Material.Resource.Drawable.xf_radio_button_unselected = global::Bleys.Droid.Resource.Drawable.xf_radio_button_unselected;
			global::XF.Material.Resource.Id.automatic = global::Bleys.Droid.Resource.Id.automatic;
			global::XF.Material.Resource.Id.bottomtab_navarea = global::Bleys.Droid.Resource.Id.bottomtab_navarea;
			global::XF.Material.Resource.Id.bottomtab_tabbar = global::Bleys.Droid.Resource.Id.bottomtab_tabbar;
			global::XF.Material.Resource.Id.flyoutcontent_appbar = global::Bleys.Droid.Resource.Id.flyoutcontent_appbar;
			global::XF.Material.Resource.Id.flyoutcontent_recycler = global::Bleys.Droid.Resource.Id.flyoutcontent_recycler;
			global::XF.Material.Resource.Id.hardware = global::Bleys.Droid.Resource.Id.hardware;
			global::XF.Material.Resource.Id.inset_drawable = global::Bleys.Droid.Resource.Id.inset_drawable;
			global::XF.Material.Resource.Id.lottie_layer_name = global::Bleys.Droid.Resource.Id.lottie_layer_name;
			global::XF.Material.Resource.Id.main_appbar = global::Bleys.Droid.Resource.Id.main_appbar;
			global::XF.Material.Resource.Id.main_tablayout = global::Bleys.Droid.Resource.Id.main_tablayout;
			global::XF.Material.Resource.Id.main_toolbar = global::Bleys.Droid.Resource.Id.main_toolbar;
			global::XF.Material.Resource.Id.main_viewpager = global::Bleys.Droid.Resource.Id.main_viewpager;
			global::XF.Material.Resource.Id.restart = global::Bleys.Droid.Resource.Id.restart;
			global::XF.Material.Resource.Id.reverse = global::Bleys.Droid.Resource.Id.reverse;
			global::XF.Material.Resource.Id.shellcontent_appbar = global::Bleys.Droid.Resource.Id.shellcontent_appbar;
			global::XF.Material.Resource.Id.shellcontent_toolbar = global::Bleys.Droid.Resource.Id.shellcontent_toolbar;
			global::XF.Material.Resource.Id.sliding_tabs = global::Bleys.Droid.Resource.Id.sliding_tabs;
			global::XF.Material.Resource.Id.software = global::Bleys.Droid.Resource.Id.software;
			global::XF.Material.Resource.Id.toolbar = global::Bleys.Droid.Resource.Id.toolbar;
			global::XF.Material.Resource.Layout.BottomTabLayout = global::Bleys.Droid.Resource.Layout.BottomTabLayout;
			global::XF.Material.Resource.Layout.FallbackTabbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::XF.Material.Resource.Layout.FallbackToolbarDoNotUse = global::Bleys.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::XF.Material.Resource.Layout.FlyoutContent = global::Bleys.Droid.Resource.Layout.FlyoutContent;
			global::XF.Material.Resource.Layout.RootLayout = global::Bleys.Droid.Resource.Layout.RootLayout;
			global::XF.Material.Resource.Layout.ShellContent = global::Bleys.Droid.Resource.Layout.ShellContent;
			global::XF.Material.Resource.Layout.Tabbar = global::Bleys.Droid.Resource.Layout.Tabbar;
			global::XF.Material.Resource.Layout.Toolbar = global::Bleys.Droid.Resource.Layout.Toolbar;
			global::XF.Material.Resource.Raw.loading_animation = global::Bleys.Droid.Resource.Raw.loading_animation;
			global::XF.Material.Resource.String.app_name = global::Bleys.Droid.Resource.String.app_name;
			global::XF.Material.Resource.String.hello = global::Bleys.Droid.Resource.String.hello;
			global::XF.Material.Resource.Style.Base_CardView = global::Bleys.Droid.Resource.Style.Base_CardView;
			global::XF.Material.Resource.Style.CardView = global::Bleys.Droid.Resource.Style.CardView;
			global::XF.Material.Resource.Style.CardView_Dark = global::Bleys.Droid.Resource.Style.CardView_Dark;
			global::XF.Material.Resource.Style.CardView_Light = global::Bleys.Droid.Resource.Style.CardView_Light;
			global::XF.Material.Resource.Style.collectionViewStyle = global::Bleys.Droid.Resource.Style.collectionViewStyle;
			global::XF.Material.Resource.Style.NestedScrollBarStyle = global::Bleys.Droid.Resource.Style.NestedScrollBarStyle;
			global::XF.Material.Resource.Styleable.CardView = global::Bleys.Droid.Resource.Styleable.CardView;
			global::XF.Material.Resource.Styleable.CardView_android_minHeight = global::Bleys.Droid.Resource.Styleable.CardView_android_minHeight;
			global::XF.Material.Resource.Styleable.CardView_android_minWidth = global::Bleys.Droid.Resource.Styleable.CardView_android_minWidth;
			global::XF.Material.Resource.Styleable.CardView_cardBackgroundColor = global::Bleys.Droid.Resource.Styleable.CardView_cardBackgroundColor;
			global::XF.Material.Resource.Styleable.CardView_cardCornerRadius = global::Bleys.Droid.Resource.Styleable.CardView_cardCornerRadius;
			global::XF.Material.Resource.Styleable.CardView_cardElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardElevation;
			global::XF.Material.Resource.Styleable.CardView_cardMaxElevation = global::Bleys.Droid.Resource.Styleable.CardView_cardMaxElevation;
			global::XF.Material.Resource.Styleable.CardView_cardPreventCornerOverlap = global::Bleys.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap;
			global::XF.Material.Resource.Styleable.CardView_cardUseCompatPadding = global::Bleys.Droid.Resource.Styleable.CardView_cardUseCompatPadding;
			global::XF.Material.Resource.Styleable.CardView_contentPadding = global::Bleys.Droid.Resource.Styleable.CardView_contentPadding;
			global::XF.Material.Resource.Styleable.CardView_contentPaddingBottom = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingBottom;
			global::XF.Material.Resource.Styleable.CardView_contentPaddingLeft = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingLeft;
			global::XF.Material.Resource.Styleable.CardView_contentPaddingRight = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingRight;
			global::XF.Material.Resource.Styleable.CardView_contentPaddingTop = global::Bleys.Droid.Resource.Styleable.CardView_contentPaddingTop;
			global::XF.Material.Resource.Styleable.LottieAnimationView = global::Bleys.Droid.Resource.Styleable.LottieAnimationView;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_autoPlay = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_autoPlay;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_cacheComposition = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_cacheComposition;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_colorFilter = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_colorFilter;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_enableMergePathsForKitKatAndAbove = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_enableMergePathsForKitKatAndAbove;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_fallbackRes = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_fallbackRes;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_fileName = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_fileName;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_imageAssetsFolder = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_imageAssetsFolder;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_loop = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_loop;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_progress = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_progress;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_rawRes = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_rawRes;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_renderMode = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_renderMode;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_repeatCount = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_repeatCount;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_repeatMode = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_repeatMode;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_scale = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_scale;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_speed = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_speed;
			global::XF.Material.Resource.Styleable.LottieAnimationView_lottie_url = global::Bleys.Droid.Resource.Styleable.LottieAnimationView_lottie_url;
			global::XF.Material.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::Bleys.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int EnterFromLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int EnterFromRight = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ExitToLeft = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExitToRight = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int material_button_state_list_anim = 2130837504;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int cardBackgroundColor = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int cardCornerRadius = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int cardElevation = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int cardMaxElevation = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int cardPreventCornerOverlap = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int cardUseCompatPadding = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int cardViewStyle = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int contentPadding = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int contentPaddingBottom = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int contentPaddingLeft = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int contentPaddingRight = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int contentPaddingTop = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int lottie_autoPlay = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int lottie_cacheComposition = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int lottie_colorFilter = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int lottie_enableMergePathsForKitKatAndAbove = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int lottie_fallbackRes = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int lottie_fileName = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int lottie_imageAssetsFolder = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int lottie_loop = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int lottie_progress = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int lottie_rawRes = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int lottie_renderMode = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int lottie_repeatCount = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int lottie_repeatMode = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int lottie_scale = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int lottie_speed = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int lottie_url = 2130903067;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int colorAccent = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int colorPrimary = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int colorPrimaryDark = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int launcher_background = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int cardview_default_radius = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int mtrl_btn_additional_padding_end_for_icon = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int mtrl_btn_additional_padding_start_for_icon = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int mtrl_btn_corner_radius = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int mtrl_btn_dialog_btn_min_width = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int mtrl_btn_disabled_elevation = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int mtrl_btn_disabled_z = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int mtrl_btn_elevation = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int mtrl_btn_focused_z = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int mtrl_btn_hovered_z = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int mtrl_btn_icon_padding = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int mtrl_btn_inset = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int mtrl_btn_letter_spacing = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int mtrl_btn_padding_bottom = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int mtrl_btn_padding_left = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int mtrl_btn_padding_left_with_icon = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int mtrl_btn_padding_right = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int mtrl_btn_padding_top = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int mtrl_btn_pressed_z = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int mtrl_btn_stroke_size = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int mtrl_btn_text_btn_icon_padding = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int mtrl_btn_text_btn_padding_left = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int mtrl_btn_text_btn_padding_right = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int mtrl_btn_text_padding_left = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int mtrl_btn_text_padding_right = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int mtrl_btn_text_size = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int mtrl_btn_z = 2131034140;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int drawable_ripple = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int drawable_ripple_image = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int drawable_ripple_outlined = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int drawable_ripple_outlined_with_icon = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int drawable_ripple_text = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int drawable_ripple_with_icon = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int drawable_selector = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int drawable_shape = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int drawable_shape_text = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int drawable_shape_with_icon = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int xamarin_logo = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int xf_arrow_dropdown = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int xf_check = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int xf_checkbox_selected = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int xf_checkbox_unselected = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int xf_clear = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int xf_error = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int xf_radio_button_selected = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int xf_radio_button_unselected = 2131099666;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int automatic = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int bottomtab_navarea = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int bottomtab_tabbar = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int collectionViewStyle = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int flyoutcontent_appbar = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int flyoutcontent_recycler = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int hardware = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int inset_drawable = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int lottie_layer_name = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int main_appbar = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int main_tablayout = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int main_toolbar = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int main_viewpager = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int mask = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int nestedScrollViewStyle = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int restart = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int reverse = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int shellcontent_appbar = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int shellcontent_toolbar = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int sliding_tabs = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int software = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int toolbar = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int BottomTabLayout = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int FallbackTabbarDoNotUse = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int FallbackToolbarDoNotUse = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int FlyoutContent = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int LoginPageLayout = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int RootLayout = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int ShellContent = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int Tabbar = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int Toolbar = 2131230728;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int icon = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int icon_round = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int launcher_foreground = 2131296258;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F0A0000
			public const int loading_animation = 2131361792;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int app_name = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int hello = 2131427329;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppCompatDialogStyle = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int Base_CardView = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int CardView = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int CardView_Dark = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int CardView_Light = 2131492868;
			
			// aapt resource value: 0x7F0C0008
			public const int collectionViewStyle = 2131492872;
			
			// aapt resource value: 0x7F0C0005
			public const int MainTheme = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int MainTheme_Base = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int NestedScrollBarStyle = 2131492871;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x101013F,0x1010140,0x7F030000,0x7F030001,0x7F030002,0x7F030003,0x7F030004,0x7F030005,0x7F030007,0x7F030008,0x7F030009,0x7F03000A,0x7F03000B }
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130903040,
					2130903041,
					2130903042,
					2130903043,
					2130903044,
					2130903045,
					2130903047,
					2130903048,
					2130903049,
					2130903050,
					2130903051};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 6
			public const int CardView_cardPreventCornerOverlap = 6;
			
			// aapt resource value: 7
			public const int CardView_cardUseCompatPadding = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingBottom = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingLeft = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingRight = 11;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingTop = 12;
			
			// aapt resource value: { 0x7F03000C,0x7F03000D,0x7F03000E,0x7F03000F,0x7F030010,0x7F030011,0x7F030012,0x7F030013,0x7F030014,0x7F030015,0x7F030016,0x7F030017,0x7F030018,0x7F030019,0x7F03001A,0x7F03001B }
			public static int[] LottieAnimationView = new int[] {
					2130903052,
					2130903053,
					2130903054,
					2130903055,
					2130903056,
					2130903057,
					2130903058,
					2130903059,
					2130903060,
					2130903061,
					2130903062,
					2130903063,
					2130903064,
					2130903065,
					2130903066,
					2130903067};
			
			// aapt resource value: 0
			public const int LottieAnimationView_lottie_autoPlay = 0;
			
			// aapt resource value: 1
			public const int LottieAnimationView_lottie_cacheComposition = 1;
			
			// aapt resource value: 2
			public const int LottieAnimationView_lottie_colorFilter = 2;
			
			// aapt resource value: 3
			public const int LottieAnimationView_lottie_enableMergePathsForKitKatAndAbove = 3;
			
			// aapt resource value: 4
			public const int LottieAnimationView_lottie_fallbackRes = 4;
			
			// aapt resource value: 5
			public const int LottieAnimationView_lottie_fileName = 5;
			
			// aapt resource value: 6
			public const int LottieAnimationView_lottie_imageAssetsFolder = 6;
			
			// aapt resource value: 7
			public const int LottieAnimationView_lottie_loop = 7;
			
			// aapt resource value: 8
			public const int LottieAnimationView_lottie_progress = 8;
			
			// aapt resource value: 9
			public const int LottieAnimationView_lottie_rawRes = 9;
			
			// aapt resource value: 10
			public const int LottieAnimationView_lottie_renderMode = 10;
			
			// aapt resource value: 11
			public const int LottieAnimationView_lottie_repeatCount = 11;
			
			// aapt resource value: 12
			public const int LottieAnimationView_lottie_repeatMode = 12;
			
			// aapt resource value: 13
			public const int LottieAnimationView_lottie_scale = 13;
			
			// aapt resource value: 14
			public const int LottieAnimationView_lottie_speed = 14;
			
			// aapt resource value: 15
			public const int LottieAnimationView_lottie_url = 15;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0E0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131623936;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
